import React,{memo,useEffect,useRef} from 'react';
import {Animated,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
const BEAD_COUNT=108;
const BEADS=Array.from({length:BEAD_COUNT},(_,i)=>{const a=i/BEAD_COUNT*Math.PI*2-Math.PI/2;return {left:`${50+43*Math.cos(a)}%`,top:`${47+39*Math.sin(a)}%`};});
export default memo(function DigitalMala({count,currentMala=1,totalMalas=1,onPress,disabled}){
  const pulse=useRef(new Animated.Value(1)).current,currentBead=count%BEAD_COUNT,roundComplete=count>0&&currentBead===0;
  useEffect(()=>{const motion=Animated.sequence([Animated.timing(pulse,{toValue:roundComplete?1.06:1.025,duration:roundComplete?350:130,useNativeDriver:true}),Animated.timing(pulse,{toValue:1,duration:roundComplete?700:220,useNativeDriver:true})]);motion.start();return()=>motion.stop();},[count,pulse,roundComplete]);
  return <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Digital 108-bead mala. Mala ${currentMala} of ${totalMalas}. Bead ${currentBead} of 108.`} accessibilityHint={disabled?'Practice counting is paused':'Counts one repetition'} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={s.touch}>
    <Animated.View pointerEvents="none" style={[s.mala,{transform:[{scale:pulse}]}]}><View style={s.thread}/><View style={s.meruThread}/><View style={s.tasselLeft}/><View style={s.tasselRight}/>
      {BEADS.map((position,i)=><View key={i} style={[s.bead,position,i<currentBead&&s.done,i===currentBead&&!roundComplete&&s.current]}/>)}<View accessibilityLabel="Meru bead, not counted" style={s.meru}/>
      <View style={s.center}><Text style={s.round}>Mala {currentMala} of {totalMalas}</Text><Text style={s.number}>{currentBead}</Text><Text style={s.label}>of 108 repetitions</Text><Text style={s.hint}>{roundComplete?'Mala complete · continuing':disabled?'Practice paused':'Tap the mala once per repetition'}</Text></View>
    </Animated.View></TouchableOpacity>;
});
const s=StyleSheet.create({touch:{width:'100%',maxWidth:350,aspectRatio:1,alignSelf:'center',marginVertical:14},mala:{flex:1},thread:{position:'absolute',left:'6.8%',right:'6.8%',top:'8%',bottom:'13%',borderWidth:2,borderColor:'#704B2A',borderRadius:999},meruThread:{position:'absolute',left:'49.6%',top:'83%',width:2,height:'9%',backgroundColor:'#704B2A'},tasselLeft:{position:'absolute',left:'47.5%',top:'91%',width:2,height:'7%',backgroundColor:'#A86A32',transform:[{rotate:'12deg'}]},tasselRight:{position:'absolute',left:'52%',top:'91%',width:2,height:'7%',backgroundColor:'#A86A32',transform:[{rotate:'-12deg'}]},bead:{position:'absolute',width:8,height:8,marginLeft:-4,marginTop:-4,borderRadius:5,backgroundColor:'#5A3C27',borderWidth:1,borderColor:'#8A633F'},done:{backgroundColor:'#D69043',borderColor:'#F1BD76'},current:{backgroundColor:'#FFF1C9',borderColor:'#FFFFFF',width:13,height:13,marginLeft:-6.5,marginTop:-6.5,borderRadius:7},meru:{position:'absolute',left:'50%',top:'84.5%',width:19,height:22,marginLeft:-9.5,borderRadius:10,backgroundColor:'#B97838',borderWidth:2,borderColor:'#F4C47E'},center:{position:'absolute',top:'28%',left:'18%',right:'18%',alignItems:'center'},round:{fontSize:13,color:'#DDBA91',fontWeight:'700'},number:{fontSize:46,color:'#F4B76D',fontWeight:'700',marginTop:5},label:{color:'#E4D0BA',fontSize:15},hint:{color:'#BEA58E',fontSize:12,textAlign:'center',marginTop:10}});
