// DharmaSetu — Katha Vault — READ-ONLY MOBILE APP
// ARCHITECTURAL CHANGE: App no longer generates content.
// All content is generated by admin (katha_admin_generator.js)
// and served from backend as Divine JSON.
// Mobile app = fetch + display only. Zero AI calls.
//
// ✅ Reads Divine JSON from backend (structured verse data)
// ✅ Sacred Scroll UI — gold borders, aura glow, Vigraha grid
// ✅ Bal-Seekh children's corner
// ✅ PDF download (Premium only)
// ✅ FlashList for smooth scrolling (no black screen)
// ✅ Lazy expand for heavy Rishi content
// ✅ No AI keys, no generation logic, no reset buttons

import AsyncStorage from '@react-native-async-storage/async-storage';
import { FlashList } from '@shopify/flash-list';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator, Alert, Animated, Modal,
  Share, StyleSheet, Text, TouchableOpacity, View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { BACKEND_URL } from '../config_keys';
// NOTE: GROQ_KEY and GEM_KEY are NOT imported here — app no longer calls AI

// ═══════════════════════════════════════════════════════════════
// SCRIPTURES
// ═══════════════════════════════════════════════════════════════
const SCRIPTURES = [
  {
    id:'bhagavad_gita', icon:'📖', name:'Bhagavad Gita', nameHi:'भगवद्गीता',
    desc:'700 shlokas · 18 Chapters · Sri Krishna to Arjuna',
    descHi:'700 श्लोक · 18 अध्याय · श्रीकृष्ण द्वारा अर्जुन को',
    color:'#E8620A', type:'gita', primaryLang:'Sanskrit',
    units:[
      {n:1, t:'Arjuna Vishada Yoga',             tH:'अर्जुन विषाद योग',              s:47},
      {n:2, t:'Sankhya Yoga',                     tH:'सांख्य योग',                    s:72},
      {n:3, t:'Karma Yoga',                       tH:'कर्म योग',                      s:43},
      {n:4, t:'Jnana Karma Sanyasa Yoga',         tH:'ज्ञान कर्म संन्यास योग',        s:42},
      {n:5, t:'Karma Sanyasa Yoga',               tH:'कर्म संन्यास योग',              s:29},
      {n:6, t:'Atmasanyama Yoga',                 tH:'आत्मसंयम योग',                  s:47},
      {n:7, t:'Jnana Vijnana Yoga',               tH:'ज्ञान विज्ञान योग',             s:30},
      {n:8, t:'Aksara Brahma Yoga',               tH:'अक्षर ब्रह्म योग',              s:28},
      {n:9, t:'Raja Vidya Raja Guhya Yoga',       tH:'राज विद्या राज गुह्य योग',      s:34},
      {n:10,t:'Vibhuti Yoga',                     tH:'विभूति योग',                    s:42},
      {n:11,t:'Vishwarupa Darshana Yoga',         tH:'विश्वरूप दर्शन योग',            s:55},
      {n:12,t:'Bhakti Yoga',                      tH:'भक्ति योग',                     s:20},
      {n:13,t:'Kshetra Kshetragnya Vibhaga Yoga', tH:'क्षेत्र क्षेत्रज्ञ विभाग योग',  s:34},
      {n:14,t:'Gunatraya Vibhaga Yoga',           tH:'गुणत्रय विभाग योग',             s:27},
      {n:15,t:'Purushottama Yoga',                tH:'पुरुषोत्तम योग',                s:20},
      {n:16,t:'Daivasura Sampad Vibhaga Yoga',    tH:'दैवासुर संपद विभाग योग',        s:24},
      {n:17,t:'Sraddhatraya Vibhaga Yoga',        tH:'श्रद्धात्रय विभाग योग',         s:28},
      {n:18,t:'Moksha Sanyasa Yoga',              tH:'मोक्ष संन्यास योग',              s:78},
    ],
  },
  {
    id:'valmiki_ramayana', icon:'🏹', name:'Valmiki Ramayana', nameHi:'वाल्मीकि रामायण',
    desc:'24,000 verses · 7 Kandas · By Maharishi Valmiki',
    descHi:'24,000 श्लोक · 7 काण्ड · महर्षि वाल्मीकि द्वारा',
    color:'#C9830A', type:'ramayana', primaryLang:'Sanskrit',
    units:[
      {n:1,t:'Bala Kanda',tH:'बाल काण्ड',s:77},{n:2,t:'Ayodhya Kanda',tH:'अयोध्या काण्ड',s:119},
      {n:3,t:'Aranya Kanda',tH:'अरण्य काण्ड',s:75},{n:4,t:'Kishkindha Kanda',tH:'किष्किन्धा काण्ड',s:67},
      {n:5,t:'Sundara Kanda',tH:'सुन्दर काण्ड',s:68},{n:6,t:'Yuddha Kanda',tH:'युद्ध काण्ड',s:131},
      {n:7,t:'Uttara Kanda',tH:'उत्तर काण्ड',s:111},
    ],
  },
  {
    id:'ramcharitmanas', icon:'🪷', name:'Ramcharitmanas', nameHi:'रामचरितमानस',
    desc:'Awadhi · Dohas & Chaupais · By Sant Tulsidas',
    descHi:'अवधी · दोहे व चौपाई · संत तुलसीदास',
    color:'#8B4513', type:'manas', primaryLang:'Awadhi',
    units:[
      {n:1,t:'Bal Kand',tH:'बाल काण्ड',s:360},{n:2,t:'Ayodhya Kand',tH:'अयोध्या काण्ड',s:326},
      {n:3,t:'Aranya Kand',tH:'अरण्य काण्ड',s:46},{n:4,t:'Kishkindha Kand',tH:'किष्किन्धा काण्ड',s:30},
      {n:5,t:'Sundar Kand',tH:'सुन्दर काण्ड',s:60},{n:6,t:'Lanka Kand',tH:'लंका काण्ड',s:117},
      {n:7,t:'Uttar Kand',tH:'उत्तर काण्ड',s:130},
    ],
  },
  {
    id:'mahabharata', icon:'⚔️', name:'Mahabharata', nameHi:'महाभारत',
    desc:'18 Parvas · Epic of Dharma · By Maharishi Vyasa',
    descHi:'18 पर्व · धर्म का महाकाव्य · महर्षि व्यास',
    color:'#6B21A8', type:'mahabharat', primaryLang:'Sanskrit',
    units:[
      {n:1,t:'Adi Parva',tH:'आदि पर्व',s:227},{n:2,t:'Sabha Parva',tH:'सभा पर्व',s:79},
      {n:3,t:'Vana Parva',tH:'वन पर्व',s:317},{n:5,t:'Udyoga Parva',tH:'उद्योग पर्व',s:199},
      {n:6,t:'Bhishma Parva',tH:'भीष्म पर्व',s:122},{n:12,t:'Shanti Parva',tH:'शांति पर्व',s:365},
      {n:18,t:'Svargarohana Parva',tH:'स्वर्गारोहण पर्व',s:5},
    ],
  },
  {
    id:'srimad_bhagavatam', icon:'🌸', name:'Srimad Bhagavatam', nameHi:'श्रीमद् भागवतम्',
    desc:'12 Skandhas · Krishna Lila · By Maharishi Vyasa',
    descHi:'12 स्कंध · श्रीकृष्ण लीला · महर्षि व्यास',
    color:'#27AE60', type:'bhagavatam', primaryLang:'Sanskrit',
    units:[
      {n:1,t:'Skandha 1',tH:'स्कंध 1',s:19},{n:7,t:'Skandha 7 — Prahlada',tH:'स्कंध 7 — प्रह्लाद',s:15},
      {n:10,t:'Skandha 10 — Krishna Lila',tH:'स्कंध 10 — कृष्ण लीला',s:90},
    ],
  },
  {
    id:'upanishads', icon:'🕉', name:'Key Upanishads', nameHi:'प्रमुख उपनिषद्',
    desc:'10 Principal Upanishads — Vedanta source',
    descHi:'10 मुख्य उपनिषद् — वेदांत का मूल',
    color:'#1A5C8B', type:'upanishad', primaryLang:'Sanskrit',
    units:[
      {n:1,t:'Isha Upanishad',tH:'ईशावास्य उपनिषद्',s:18},
      {n:3,t:'Katha Upanishad',tH:'कठ उपनिषद्',s:119},
      {n:5,t:'Mundaka Upanishad',tH:'मुण्डक उपनिषद्',s:64},
      {n:9,t:'Chandogya Upanishad',tH:'छांदोग्य उपनिषद्',s:154},
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// CACHE — AsyncStorage, permanent
// ═══════════════════════════════════════════════════════════════
const CV = 'kv_ro1_'; // "read-only v1" — fresh key, no old broken data

async function getCached(sid, n, lang) {
  try { const r = await AsyncStorage.getItem(`${CV}${sid}_${n}_${lang}`); return r ? JSON.parse(r) : null; }
  catch { return null; }
}
async function saveCache(sid, n, lang, data) {
  try { await AsyncStorage.setItem(`${CV}${sid}_${n}_${lang}`, JSON.stringify(data)); } catch {}
}
async function getProgress(sid) {
  try { const r = await AsyncStorage.getItem(`kp_ro1_${sid}`); return r ? JSON.parse(r) : {}; } catch { return {}; }
}
async function markRead(sid, n) {
  try { const p = await getProgress(sid); p[n] = Date.now(); await AsyncStorage.setItem(`kp_ro1_${sid}`, JSON.stringify(p)); } catch {}
}

// ═══════════════════════════════════════════════════════════════
// FETCH FROM BACKEND — read-only, no AI
// ═══════════════════════════════════════════════════════════════
async function fetchChapter(sc, unit, lang) {
  // 1. Local cache
  const cached = await getCached(sc.id, unit.n, lang);
  if (cached?.verses?.length > 0) return { verses: cached.verses, source: 'cache' };

  // 2. Backend
  try {
    const res = await fetch(`${BACKEND_URL}/katha/${sc.id}/${unit.n}/${lang}`, {
      signal: AbortSignal.timeout(12000),
    });
    if (res.ok) {
      const d = await res.json();
      if (d?.content) {
        let verses;
        try {
          // Try Divine JSON first
          const parsed = typeof d.content === 'string' ? JSON.parse(d.content) : d.content;
          verses = Array.isArray(parsed) ? parsed : null;
        } catch {
          verses = null;
        }
        if (verses && verses.length > 0) {
          await saveCache(sc.id, unit.n, lang, { verses, ts: Date.now() });
          await markRead(sc.id, unit.n);
          return { verses, source: 'backend' };
        }
        // Old text format — wrap as single verse for display
        if (typeof d.content === 'string' && d.content.length > 100) {
          const wrapped = [{ verse_id: `${unit.n}.text`, sanskrit_full: '', tika_hindi: d.content, tika_english: d.content }];
          return { verses: wrapped, source: 'backend_text' };
        }
      }
    }
  } catch(e) {
    console.log('[Katha] Backend fetch failed:', e.message);
  }

  // 3. Not yet generated by admin
  return { verses: null, source: 'not_ready' };
}

// ═══════════════════════════════════════════════════════════════
// PDF — Premium only, Sacred Scroll branded
// ═══════════════════════════════════════════════════════════════
async function downloadAsPDF(sc, unit, lang, verses, userProfile) {
  if (!userProfile || userProfile.plan === 'free') {
    const isH = userProfile?.language === 'hindi';
    Alert.alert(
      '🙏 Premium Feature',
      isH
        ? 'PDF Download Premium सदस्यों के लिए है।\n\nसनातन धर्म की रक्षा में सहयोग करें।'
        : 'PDF Download is a Premium feature.\n\nSupport the preservation of our heritage.',
      [
        { text: isH ? 'बाद में' : 'Later', style: 'cancel' },
        { text: isH ? '⭐ Premium लें' : '⭐ Upgrade',
          onPress: () => router.push('/(tabs)/payment') },
      ]
    );
    return;
  }

  try {
    const isH = lang === 'hindi';
    const scName = isH ? sc.nameHi : sc.name;
    const uTitle = isH ? unit.tH : unit.t;
    let body = '';

    for (const v of verses) {
      const san = v.sanskrit_full || '';
      const rom = v.roman_transliteration || '';
      const tika = isH ? (v.tika_hindi || v.tika_english || '') : (v.tika_english || v.tika_hindi || '');
      const rishi = v.gahan_drishti || '';
      const bal = v.bal_seekh || '';
      const words = v.word_meanings_grid || [];

      body += `<div class="sh">🕉 ${v.verse_id}</div>`;
      if (san) body += `<div class="san">${san.replace(/\n/g,'<br/>')}</div>`;
      if (rom) body += `<div class="rom">${rom}</div>`;
      if (words.length > 0) {
        body += `<div class="vhdr">📚 Vigraha</div><div class="vgrid">`;
        words.forEach(w => { body += `<div class="vc">${w.word}: ${w.meaning}</div>`; });
        body += `</div>`;
      }
      if (tika) body += `<div class="tika"><b>Tika:</b> ${tika}</div>`;
      if (rishi) body += `<div class="rishi">🔱 Gahan Drishti<br/><em>${rishi}</em></div>`;
      if (bal) body += `<div class="bal">🌟 Bal-Seekh: ${bal}</div>`;
      body += `<hr/>`;
    }

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<style>
  body{font-family:Georgia,serif;background:#FFFDF7;color:#2C1800;padding:24px;font-size:13px}
  .brand{background:#8B4513;color:#FFF8E1;text-align:center;padding:10px;margin:-24px -24px 24px;font-size:12px}
  .cover{text-align:center;padding:28px 0 20px;border-bottom:2px solid #C9830A;margin-bottom:24px}
  .sh{background:#FFF3E0;border-left:4px solid #E8620A;padding:8px 12px;margin:20px 0 8px;font-weight:bold;font-size:12px;color:#C45508;border-radius:4px;border:1px solid #FFD700}
  .san{background:#EDE7F6;border-radius:8px;padding:14px;margin:6px 0;font-size:18px;color:#4A148C;line-height:2.2;text-align:center;font-weight:600;border:1px solid #D4AF37}
  .rom{color:#6A1B9A;font-style:italic;font-size:12px;padding:2px 12px 8px;line-height:1.6}
  .vhdr{background:#FFF8E1;border:1px solid #C9830A;padding:5px 10px;margin:8px 0 4px;font-size:11px;font-weight:bold;color:#8B6914;border-radius:4px}
  .vgrid{display:flex;flex-wrap:wrap;gap:4px;margin-bottom:8px}
  .vc{background:#FFFDE7;border:1px solid #C9830A;padding:4px 8px;font-size:11px;border-radius:4px;color:#5D4037}
  .tika{background:#FBE9E7;border-radius:6px;padding:10px;margin:6px 0;font-size:13px;line-height:1.7}
  .rishi{background:#EDE7F6;border:1px solid #7B1FA2;border-left:4px solid #9C27B0;border-radius:8px;padding:12px;margin:8px 0;font-size:13px;color:#4A148C;line-height:1.8}
  .bal{background:rgba(255,215,0,0.1);border:1px solid #FFD700;border-radius:6px;padding:8px 12px;margin:6px 0;font-size:12px;color:#8B6914}
  hr{border:0.5px solid #C9830A;margin:12px 0;opacity:0.4}
  .foot{border-top:1px solid #C9830A;margin-top:28px;padding-top:12px;text-align:center;font-size:11px;color:#8B4513}
</style></head><body>
<div class="brand">🕉 DharmaSetu — Your Digital Gurukul | dharmasetu.in</div>
<div class="cover">
  <div style="font-size:40px">🕉</div>
  <h1 style="color:#8B4513;margin:8px 0 4px">${scName}</h1>
  <h2 style="color:#C9830A;font-weight:normal;margin:0">${uTitle}</h2>
</div>
${body}
<div class="foot">🕉 DharmaSetu — Your Digital Gurukul<br/>dharmasetu.in | जय सनातन धर्म</div>
</body></html>`;

    const { uri } = await Print.printToFileAsync({ html, base64: false });
    const ok = await Sharing.isAvailableAsync();
    if (ok) await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf' });
    else Alert.alert('PDF Ready', uri);

  } catch(e) {
    try { await Share.share({ message: verses.map(v => `${v.verse_id}\n${v.sanskrit_full||''}\n${v.tika_hindi||v.tika_english||''}`).join('\n\n'), title: `DharmaSetu` }); }
    catch { Alert.alert('Error', e.message); }
  }
}

// ═══════════════════════════════════════════════════════════════
// SHLOKA CARD — Sacred Scroll, lazy Rishi expand
// ═══════════════════════════════════════════════════════════════
function ShlokaCard({ verse, lang, index }) {
  const [expanded, setExpanded] = useState(false);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const isH = lang === 'hindi';
  const FS = 14;

  useEffect(() => {
    Animated.timing(fadeAnim, { toValue: 1, duration: 350, delay: Math.min(index * 40, 400), useNativeDriver: true }).start();
  }, []);

  const tika  = isH ? (verse.tika_hindi || verse.tika_english || '') : (verse.tika_english || verse.tika_hindi || '');
  const words = verse.word_meanings_grid || [];
  const rishi = verse.gahan_drishti || '';
  const bal   = verse.bal_seekh || '';
  const teach = verse.teaching || '';

  return (
    <Animated.View style={[vc.card, { opacity: fadeAnim }]}>
      {/* Verse ID header */}
      <View style={vc.verseHdr}>
        <Text style={vc.omIcon}>ॐ</Text>
        <Text style={vc.verseId}>{verse.verse_id}</Text>
        {verse.speaker && <Text style={vc.speaker}>{verse.speaker}</Text>}
      </View>

      {/* Sanskrit — always visible */}
      {verse.sanskrit_full ? (
        <View style={vc.sanCard}>
          <Text style={[vc.sanTxt, {fontSize: FS + 3, lineHeight: (FS + 3) * 2.1}]}>
            {verse.sanskrit_full}
          </Text>
        </View>
      ) : null}

      {/* Transliteration */}
      {verse.roman_transliteration ? (
        <Text style={[vc.romTxt, {fontSize: FS - 1}]}>{verse.roman_transliteration}</Text>
      ) : null}

      {/* Vigraha — 2-column chip grid */}
      {words.length > 0 && (
        <View style={vc.vigrahaCard}>
          <View style={vc.vigrahaHdrRow}>
            <Text style={vc.vigrahaIcon}>📚</Text>
            <Text style={vc.vigrahaHdrTxt}>{isH ? 'शब्द-अर्थ' : 'Word Meanings'}</Text>
          </View>
          <View style={vc.vigrahaGrid}>
            {words.map((w, i) => (
              <View key={i} style={vc.chip}>
                <Text style={[vc.chipWord, {fontSize: FS - 2}]}>{w.word}</Text>
                <Text style={[vc.chipMeaning, {fontSize: FS - 3}]}>{w.meaning}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Tika — always visible */}
      {tika ? (
        <View style={vc.tikaCard}>
          <Text style={vc.tikaLbl}>🔱 {isH ? 'गीता प्रेस तिका' : 'Gita Press Tika'}</Text>
          <Text style={[vc.tikaTxt, {fontSize: FS, lineHeight: FS * 1.9}]}>{tika}</Text>
        </View>
      ) : null}

      {/* Teaching */}
      {teach ? (
        <View style={vc.bodhCard}>
          <Text style={[vc.bodhTxt, {fontSize: FS - 1, lineHeight: (FS - 1) * 1.7}]}>
            🕉 {teach}
          </Text>
        </View>
      ) : null}

      {/* Rishi — LAZY: tap to expand (prevents black screen during fast scroll) */}
      {rishi ? (
        <TouchableOpacity onPress={() => setExpanded(e => !e)} activeOpacity={0.8}>
          <View style={vc.rishiCard}>
            <Text style={vc.rishiLbl}>🔱 {isH ? 'गहन दृष्टि' : 'Gahan Drishti'}</Text>
            {expanded ? (
              <Text style={[vc.rishiTxt, {fontSize: FS, lineHeight: FS * 1.9}]}>{rishi}</Text>
            ) : (
              <Text style={vc.rishiPreview}>
                {rishi.slice(0, 80)}... <Text style={vc.tapMore}>{isH ? 'पढ़ें ▼' : 'Read ▼'}</Text>
              </Text>
            )}
          </View>
        </TouchableOpacity>
      ) : null}

      {/* Bal-Seekh */}
      {bal ? (
        <View style={vc.balCard}>
          <Text style={vc.balLbl}>🌟 {isH ? 'बाल-शिक्षा' : 'Bal-Seekh'}</Text>
          <Text style={[vc.balTxt, {fontSize: FS - 1, lineHeight: (FS - 1) * 1.7}]}>{bal}</Text>
        </View>
      ) : null}
    </Animated.View>
  );
}

const vc = StyleSheet.create({
  card:         {marginBottom:16,borderRadius:16,overflow:'hidden',borderWidth:1,borderColor:'rgba(201,131,10,0.2)',backgroundColor:'#0F0600'},
  verseHdr:     {flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'rgba(232,98,10,0.12)',paddingHorizontal:14,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'rgba(232,98,10,0.15)'},
  omIcon:       {fontSize:16,color:'#E8620A',fontWeight:'800'},
  verseId:      {fontSize:13,fontWeight:'800',color:'#E8620A',letterSpacing:0.5,flex:1},
  speaker:      {fontSize:10,color:'rgba(253,246,237,0.35)',fontStyle:'italic'},
  sanCard:      {backgroundColor:'rgba(107,33,168,0.14)',padding:16,borderBottomWidth:1,borderBottomColor:'rgba(107,33,168,0.2)',shadowColor:'#FFD700',shadowOpacity:0.15,shadowRadius:6,elevation:2},
  sanTxt:       {color:'#D4A8FF',fontWeight:'600',textAlign:'center'},
  romTxt:       {color:'rgba(212,168,255,0.65)',fontStyle:'italic',paddingHorizontal:14,paddingVertical:6,lineHeight:20,fontSize:12},
  vigrahaCard:  {backgroundColor:'rgba(201,131,10,0.07)',padding:12,borderTopWidth:1,borderTopColor:'rgba(201,131,10,0.1)'},
  vigrahaHdrRow:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:8},
  vigrahaIcon:  {fontSize:13},
  vigrahaHdrTxt:{fontSize:11,fontWeight:'800',color:'#C9830A'},
  vigrahaGrid:  {flexDirection:'row',flexWrap:'wrap',gap:5},
  chip:         {backgroundColor:'rgba(201,131,10,0.12)',borderRadius:8,paddingHorizontal:9,paddingVertical:5,borderWidth:1,borderColor:'rgba(201,131,10,0.28)'},
  chipWord:     {color:'rgba(253,220,130,0.95)',fontWeight:'700'},
  chipMeaning:  {color:'rgba(253,220,130,0.6)',marginTop:1},
  tikaCard:     {backgroundColor:'rgba(232,98,10,0.07)',padding:14,borderTopWidth:1,borderTopColor:'rgba(232,98,10,0.12)'},
  tikaLbl:      {fontSize:10,color:'#E8620A',fontWeight:'800',marginBottom:6,letterSpacing:0.4},
  tikaTxt:      {color:'rgba(253,246,237,0.9)',fontWeight:'500'},
  bodhCard:     {backgroundColor:'rgba(39,174,96,0.07)',paddingHorizontal:14,paddingVertical:10,borderTopWidth:1,borderTopColor:'rgba(39,174,96,0.1)'},
  bodhTxt:      {color:'rgba(100,220,150,0.9)',fontWeight:'600'},
  rishiCard:    {backgroundColor:'rgba(255,140,0,0.06)',padding:14,borderTopWidth:1,borderTopColor:'rgba(255,140,0,0.12)',borderBottomWidth:0},
  rishiLbl:     {fontSize:10,color:'#FF8C00',fontWeight:'800',marginBottom:6,letterSpacing:0.3},
  rishiTxt:     {color:'rgba(255,220,150,0.95)',fontStyle:'italic',lineHeight:26},
  rishiPreview: {color:'rgba(255,220,150,0.7)',fontSize:13,lineHeight:20},
  tapMore:      {color:'#FF8C00',fontWeight:'700'},
  balCard:      {backgroundColor:'rgba(255,215,0,0.07)',padding:12,borderTopWidth:1,borderTopColor:'rgba(255,215,0,0.15)'},
  balLbl:       {fontSize:10,color:'#FFD700',fontWeight:'800',marginBottom:5},
  balTxt:       {color:'rgba(255,240,180,0.9)',fontWeight:'500'},
});

// ═══════════════════════════════════════════════════════════════
// CHAPTER READER — FlashList for smooth scrolling
// ═══════════════════════════════════════════════════════════════
function ChapterReader({visible, onClose, sc, unit, lang}) {
  const [verses,  setVerses]  = useState([]);
  const [loading, setLoading] = useState(true);
  const [status,  setStatus]  = useState('');
  const [notReady,setNotReady]= useState(false);
  const userProfileRef = useRef(null);
  const insets = useSafeAreaInsets();
  const isH = lang === 'hindi';

  useEffect(() => {
    if (!visible || !sc || !unit) return;
    setVerses([]); setLoading(true); setStatus(''); setNotReady(false);
    AsyncStorage.getItem('dharmasetu_user').then(raw => {
      if (raw) userProfileRef.current = JSON.parse(raw);
    });
    load();
  }, [visible, sc?.id, unit?.n, lang]);

  const load = async () => {
    setStatus(isH ? '☁️ डेटा लोड हो रहा है...' : '☁️ Loading...');
    const { verses: v, source } = await fetchChapter(sc, unit, lang);
    if (v && v.length > 0) {
      setVerses(v);
    } else {
      setNotReady(true);
    }
    setLoading(false);
  };

  const scTitle = isH ? sc?.nameHi : sc?.name;
  const uTitle  = isH ? unit?.tH   : unit?.t;

  const renderItem = useCallback(({ item, index }) => (
    <ShlokaCard verse={item} lang={lang} index={index}/>
  ), [lang]);

  const keyExtractor = useCallback((item) => item.verse_id || String(Math.random()), []);

  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
      <View style={[cr.root, {paddingTop: insets.top}]}>
        <StatusBar style="light" backgroundColor="#0A0300"/>

        {/* HEADER */}
        <View style={cr.hdr}>
          <TouchableOpacity onPress={onClose} style={cr.back} hitSlop={{top:14,bottom:14,left:14,right:14}}>
            <Text style={cr.backTxt}>←</Text>
          </TouchableOpacity>
          <View style={{flex:1}}>
            <Text style={cr.hdrSc} numberOfLines={1}>{scTitle}</Text>
            <Text style={cr.hdrTitle} numberOfLines={1}>{uTitle}</Text>
          </View>
          {verses.length > 0 && (
            <TouchableOpacity style={cr.dlBtn}
              onPress={() => downloadAsPDF(sc, unit, lang, verses, userProfileRef.current)}
              hitSlop={{top:8,bottom:8,left:8,right:8}}>
              <Text style={{fontSize:15}}>⬇️</Text>
            </TouchableOpacity>
          )}
          <TouchableOpacity style={cr.shareBtn} onPress={() => {
            if (!verses.length) return;
            const preview = verses.slice(0,3).map(v => `${v.verse_id}\n${v.sanskrit_full||''}`).join('\n\n');
            Share.share({ message:`🕉 ${scTitle} — ${uTitle}\n\n${preview}\n\n— DharmaSetu App` });
          }}>
            <Text style={{fontSize:15}}>📤</Text>
          </TouchableOpacity>
        </View>

        {loading ? (
          <View style={cr.center}>
            <ActivityIndicator size="large" color="#E8620A"/>
            <Text style={cr.loadTxt}>{isH ? 'शास्त्र लोड हो रहे हैं...' : 'Loading scripture...'}</Text>
            <Text style={cr.loadSub}>{status}</Text>
          </View>
        ) : notReady ? (
          <View style={cr.center}>
            <Text style={{fontSize:44, marginBottom:16}}>🕉</Text>
            <Text style={cr.notReadyTitle}>{isH ? 'शीघ्र आ रहा है' : 'Coming Soon'}</Text>
            <Text style={cr.notReadyTxt}>
              {isH
                ? 'यह अध्याय हमारे विद्वान तैयार कर रहे हैं।\nजल्द ही उपलब्ध होगा। 🙏'
                : 'Our scholars are preparing this chapter.\nCheck back soon. 🙏'}
            </Text>
            <TouchableOpacity style={cr.retryBtn} onPress={() => { setLoading(true); setNotReady(false); load(); }}>
              <Text style={cr.retryTxt}>{isH ? 'दोबारा जांचें' : 'Check Again'}</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <FlashList
            data={verses}
            renderItem={renderItem}
            keyExtractor={keyExtractor}
            estimatedItemSize={320}
            contentContainerStyle={{padding:14}}
            ListHeaderComponent={() => (
              <View style={{alignItems:'center',marginBottom:20,paddingBottom:16,borderBottomWidth:1,borderBottomColor:'rgba(240,165,0,0.1)'}}>
                <Text style={{fontSize:20,fontWeight:'800',color:'#F4A261',textAlign:'center',marginBottom:4}}>{uTitle}</Text>
                {unit?.s && <Text style={{fontSize:11,color:'rgba(253,246,237,0.3)'}}>{unit.s} {isH?'श्लोक':'verses'}</Text>}
                {verses.length < (unit?.s||0) && (
                  <Text style={{fontSize:10,color:'rgba(232,98,10,0.6)',marginTop:4}}>
                    {isH ? `${verses.length}/${unit.s} श्लोक उपलब्ध` : `${verses.length}/${unit.s} verses available`}
                  </Text>
                )}
              </View>
            )}
            ListFooterComponent={() => (
              <View style={{alignItems:'center',paddingVertical:24,borderTopWidth:1,borderTopColor:'rgba(240,165,0,0.1)'}}>
                <Text style={{fontSize:28,marginBottom:8}}>🕉</Text>
                <Text style={{fontSize:13,fontWeight:'700',color:'#F4A261',marginBottom:3}}>
                  {uTitle} — {isH?'पाठ पूर्ण':'Complete'}
                </Text>
                {verses.length > 0 && (
                  <TouchableOpacity
                    style={{marginTop:10,flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'rgba(232,98,10,0.1)',borderRadius:10,paddingHorizontal:14,paddingVertical:9,borderWidth:1,borderColor:'rgba(232,98,10,0.25)'}}
                    onPress={() => downloadAsPDF(sc, unit, lang, verses, userProfileRef.current)}>
                    <Text style={{fontSize:14}}>⬇️</Text>
                    <Text style={{fontSize:12,color:'#F4A261',fontWeight:'700'}}>
                      {isH?'PDF Download करें':'Download as PDF'}
                    </Text>
                  </TouchableOpacity>
                )}
                <Text style={{fontSize:12,color:'#C9830A',marginTop:12}}>जय सनातन धर्म · Jai Sanatan Dharma</Text>
                <View style={{height:insets.bottom+20}}/>
              </View>
            )}
          />
        )}
      </View>
    </Modal>
  );
}

const cr = StyleSheet.create({
  root:         {flex:1,backgroundColor:'#080200'},
  hdr:          {flexDirection:'row',alignItems:'center',paddingHorizontal:14,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'rgba(240,165,0,0.12)',gap:6},
  back:         {width:38,height:38,borderRadius:19,backgroundColor:'rgba(255,255,255,0.07)',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(240,165,0,0.18)'},
  backTxt:      {fontSize:20,color:'#F4A261',fontWeight:'600',marginTop:-1},
  hdrSc:        {fontSize:10,color:'#C9830A',fontWeight:'600',marginBottom:1},
  hdrTitle:     {fontSize:13,fontWeight:'800',color:'#F4A261'},
  dlBtn:        {paddingHorizontal:8,paddingVertical:6,borderRadius:8,backgroundColor:'rgba(39,174,96,0.12)',borderWidth:1,borderColor:'rgba(39,174,96,0.3)'},
  shareBtn:     {paddingHorizontal:8,paddingVertical:6,borderRadius:8,backgroundColor:'rgba(232,98,10,0.1)',borderWidth:1,borderColor:'rgba(232,98,10,0.25)'},
  center:       {flex:1,alignItems:'center',justifyContent:'center',padding:28},
  loadTxt:      {fontSize:15,color:'#F4A261',textAlign:'center',marginTop:16,fontWeight:'700'},
  loadSub:      {fontSize:12,color:'rgba(253,246,237,0.45)',marginTop:6,textAlign:'center'},
  notReadyTitle:{fontSize:20,fontWeight:'800',color:'#F4A261',marginBottom:10},
  notReadyTxt:  {fontSize:14,color:'rgba(253,246,237,0.6)',textAlign:'center',lineHeight:24,marginBottom:24},
  retryBtn:     {backgroundColor:'rgba(232,98,10,0.15)',paddingHorizontal:24,paddingVertical:11,borderRadius:12,borderWidth:1,borderColor:'rgba(232,98,10,0.35)'},
  retryTxt:     {fontSize:14,color:'#F4A261',fontWeight:'700'},
});

// ═══════════════════════════════════════════════════════════════
// UNIT LIST
// ═══════════════════════════════════════════════════════════════
function UnitList({visible, onClose, sc, lang, onSelect}) {
  const [prog, setProg] = useState({});
  const insets = useSafeAreaInsets();
  const isH = lang === 'hindi';
  useEffect(() => { if (visible && sc) getProgress(sc.id).then(setProg); }, [visible, sc?.id]);
  if (!sc) return null;
  const rc = Object.keys(prog).length, tot = sc.units?.length || 0;

  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
      <View style={[ul.root, {paddingTop: insets.top}]}>
        <StatusBar style="light" backgroundColor="#0D0500"/>
        <View style={ul.hdr}>
          <TouchableOpacity onPress={onClose} style={ul.back} hitSlop={{top:14,bottom:14,left:14,right:14}}>
            <Text style={ul.backTxt}>←</Text>
          </TouchableOpacity>
          <View style={{flex:1}}>
            <Text style={ul.hTitle}>{isH ? sc.nameHi : sc.name}</Text>
            <Text style={ul.hSub} numberOfLines={2}>{isH ? sc.descHi : sc.desc}</Text>
          </View>
        </View>
        <View style={ul.progBox}>
          <View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:6}}>
            <Text style={ul.progLbl}>{isH ? `${rc}/${tot} पढ़े` : `${rc}/${tot} read`}</Text>
            <Text style={[ul.progPct, {color:sc.color}]}>{Math.round((rc/Math.max(tot,1))*100)}%</Text>
          </View>
          <View style={ul.progTrack}><View style={[ul.progFill, {width:`${Math.round((rc/Math.max(tot,1))*100)}%`, backgroundColor:sc.color}]}/></View>
        </View>
        <FlashList
          data={sc.units || []}
          estimatedItemSize={72}
          contentContainerStyle={{padding:14}}
          keyExtractor={(item) => String(item.n)}
          renderItem={({item:unit}) => {
            const done = !!prog[unit.n];
            return (
              <TouchableOpacity
                style={[ul.card, {borderColor:done?sc.color+'45':'rgba(200,130,40,0.12)', backgroundColor:done?sc.color+'08':'#130700', marginBottom:8}]}
                onPress={() => onSelect(unit)} activeOpacity={0.85}>
                <View style={[ul.num, {backgroundColor:sc.color+'1A', borderColor:sc.color+'45'}]}>
                  <Text style={[ul.numTxt, {color:sc.color}]}>{unit.n}</Text>
                </View>
                <View style={{flex:1}}>
                  <Text style={ul.uTitle}>{isH ? unit.tH : unit.t}</Text>
                  {unit.s && <Text style={ul.uMeta}>{unit.s} {isH?'श्लोक':'verses'}</Text>}
                </View>
                <View style={{flexDirection:'row',alignItems:'center',gap:5}}>
                  {done && <Text style={{fontSize:12,color:'#27AE60',fontWeight:'800'}}>✓</Text>}
                  <Text style={{fontSize:20,color:'rgba(253,246,237,0.2)'}}>›</Text>
                </View>
              </TouchableOpacity>
            );
          }}
          ListFooterComponent={<View style={{height:insets.bottom+20}}/>}
        />
      </View>
    </Modal>
  );
}

const ul = StyleSheet.create({
  root:{flex:1,backgroundColor:'#0D0500'},
  hdr:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'rgba(240,165,0,0.1)',gap:12},
  back:{width:38,height:38,borderRadius:19,backgroundColor:'rgba(255,255,255,0.08)',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(240,165,0,0.2)'},
  backTxt:{fontSize:20,color:'#F4A261',fontWeight:'600',marginTop:-1},
  hTitle:{fontSize:17,fontWeight:'800',color:'#F4A261',marginBottom:2},
  hSub:{fontSize:10,color:'rgba(253,246,237,0.38)',lineHeight:15},
  progBox:{marginHorizontal:16,marginVertical:10,backgroundColor:'rgba(255,255,255,0.04)',borderRadius:12,padding:14,borderWidth:1,borderColor:'rgba(240,165,0,0.08)'},
  progLbl:{fontSize:11,color:'rgba(253,246,237,0.42)',fontWeight:'600'},
  progPct:{fontSize:11,fontWeight:'800'},
  progTrack:{height:4,backgroundColor:'rgba(255,255,255,0.06)',borderRadius:2,overflow:'hidden'},
  progFill:{height:4,borderRadius:2},
  card:{borderRadius:14,padding:14,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1},
  num:{width:38,height:38,borderRadius:10,alignItems:'center',justifyContent:'center',borderWidth:1,flexShrink:0},
  numTxt:{fontSize:14,fontWeight:'800'},
  uTitle:{fontSize:13,fontWeight:'700',color:'#FDF6ED',marginBottom:2},
  uMeta:{fontSize:10,color:'rgba(253,246,237,0.22)',marginTop:1},
});

// ═══════════════════════════════════════════════════════════════
// MAIN KATHA VAULT SCREEN
// ═══════════════════════════════════════════════════════════════
export default function KathaVault() {
  const insets = useSafeAreaInsets();
  const [lang,       setLang]      = useState('hindi');
  const [allProg,    setAllProg]   = useState({});
  const [selSc,      setSelSc]     = useState(null);
  const [selUnit,    setSelUnit]   = useState(null);
  const [showUnits,  setShowUnits] = useState(false);
  const [showReader, setShowReader]= useState(false);
  const fade = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    (async () => {
      const raw = await AsyncStorage.getItem('dharmasetu_user');
      if (raw) { const u = JSON.parse(raw); setLang(u.language || 'hindi'); }
      refresh();
    })();
    Animated.timing(fade, {toValue:1, duration:500, useNativeDriver:true}).start();
  }, []);

  const refresh = useCallback(async () => {
    const p = {};
    for (const sc of SCRIPTURES) { p[sc.id] = await getProgress(sc.id); }
    setAllProg(p);
  }, []);

  const isH = lang === 'hindi';

  return (
    <View style={[ms.root, {paddingTop: insets.top}]}>
      <StatusBar style="light" backgroundColor="#0D0500"/>
      <View style={ms.hdr}>
        <TouchableOpacity onPress={() => router.back()} style={ms.back} hitSlop={{top:14,bottom:14,left:14,right:14}}>
          <Text style={ms.backTxt}>←</Text>
        </TouchableOpacity>
        <View style={{flex:1, marginLeft:10}}>
          <Text style={ms.hTitle}>{isH ? 'कथा वॉल्ट' : 'Katha Vault'}</Text>
          <Text style={ms.hSub}>{isH ? 'पवित्र सनातन ग्रंथ' : 'Sacred Sanatan Scriptures'}</Text>
        </View>
        <View style={{flexDirection:'row', gap:5}}>
          {[{id:'hindi',l:'हिं'},{id:'english',l:'EN'}].map(({id,l}) => (
            <TouchableOpacity key={id} style={[ms.lBtn, lang===id&&ms.lBtnOn]} onPress={() => setLang(id)}>
              <Text style={[ms.lTxt, lang===id&&ms.lTxtOn]}>{l}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <FlashList
        data={SCRIPTURES}
        estimatedItemSize={160}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{padding:14}}
        renderItem={({item:sc}) => {
          const p   = allProg[sc.id] || {};
          const rc  = Object.keys(p).length;
          const tot = sc.units?.length || 1;
          const pct = Math.round((rc/tot)*100);
          return (
            <Animated.View style={{opacity:fade,marginBottom:12}}>
              <TouchableOpacity
                style={[ms.card, {borderColor:sc.color+'30'}]}
                onPress={() => {setSelSc(sc); setShowUnits(true);}}
                activeOpacity={0.88}>
                <View style={ms.cardTop}>
                  <View style={[ms.iconBox, {backgroundColor:sc.color+'18'}]}>
                    <Text style={{fontSize:26}}>{sc.icon}</Text>
                  </View>
                  <View style={{flex:1, marginLeft:14}}>
                    <Text style={ms.scName}>{isH ? sc.nameHi : sc.name}</Text>
                    <Text style={ms.scDesc} numberOfLines={2}>{isH ? sc.descHi : sc.desc}</Text>
                    <Text style={[ms.scLang, {color:sc.color}]}>{sc.primaryLang}</Text>
                  </View>
                  <Text style={{fontSize:20,color:'rgba(253,246,237,0.2)'}}>›</Text>
                </View>
                <View style={{marginTop:10}}>
                  <View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:5}}>
                    <Text style={ms.progLbl}>{isH?`${rc}/${tot} पढ़े`:`${rc}/${tot} read`}</Text>
                    <Text style={[ms.progPct,{color:sc.color}]}>{pct}%</Text>
                  </View>
                  <View style={ms.progTrack}><View style={[ms.progFill,{width:`${pct}%`,backgroundColor:sc.color}]}/></View>
                </View>
              </TouchableOpacity>
            </Animated.View>
          );
        }}
        ListFooterComponent={<View style={{height:insets.bottom+24}}/>}
      />

      <UnitList visible={showUnits} onClose={() => {setShowUnits(false); refresh();}}
        sc={selSc} lang={lang} onSelect={unit => {setSelUnit(unit); setShowReader(true);}}/>
      <ChapterReader visible={showReader} onClose={() => {setShowReader(false); refresh();}}
        sc={selSc} unit={selUnit} lang={lang}/>
    </View>
  );
}

const ms = StyleSheet.create({
  root:{flex:1,backgroundColor:'#0D0500'},
  hdr:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'rgba(240,165,0,0.1)'},
  back:{width:38,height:38,borderRadius:19,backgroundColor:'rgba(255,255,255,0.08)',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(240,165,0,0.2)'},
  backTxt:{fontSize:20,color:'#F4A261',fontWeight:'600',marginTop:-1},
  hTitle:{fontSize:19,fontWeight:'800',color:'#F4A261'},
  hSub:{fontSize:11,color:'rgba(253,246,237,0.38)',marginTop:2},
  lBtn:{paddingHorizontal:10,paddingVertical:7,borderRadius:8,borderWidth:1,borderColor:'rgba(200,130,40,0.2)'},
  lBtnOn:{backgroundColor:'rgba(232,98,10,0.15)',borderColor:'#E8620A'},
  lTxt:{fontSize:12,color:'rgba(253,246,237,0.4)',fontWeight:'700'},
  lTxtOn:{color:'#F4A261'},
  card:{backgroundColor:'#130700',borderRadius:18,padding:16,borderWidth:1},
  cardTop:{flexDirection:'row',alignItems:'center'},
  iconBox:{width:54,height:54,borderRadius:13,alignItems:'center',justifyContent:'center',flexShrink:0},
  scName:{fontSize:16,fontWeight:'800',color:'#FDF6ED',marginBottom:3},
  scDesc:{fontSize:11,color:'rgba(253,246,237,0.38)',lineHeight:16},
  scLang:{fontSize:10,fontWeight:'700',marginTop:3},
  progLbl:{fontSize:10,color:'rgba(253,246,237,0.38)'},
  progPct:{fontSize:10,fontWeight:'800'},
  progTrack:{height:4,backgroundColor:'rgba(255,255,255,0.06)',borderRadius:2,overflow:'hidden'},
  progFill:{height:4,borderRadius:2},
});