import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ActivityIndicator,Alert,AppState,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,Vibration,View} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {backendFetch} from '../utils/backend-config';
import mantraCatalog from '../utils/mantraCatalog';
import mantraPractice from '../utils/mantraPractice';
import experience from '../utils/mantraExperience';
import guided from '../utils/mantraGuided';
import {createPlaybackAdapter} from '../utils/mantraPlayback';
import {loadPractice,persistPractice} from '../utils/mantraProgressStorage';
import {useMantraPronunciation} from '../utils/useMantraPronunciation';
import {addRecentId} from '../utils/mantraLibraryStorage';
import DigitalMala from '../components/mantra/DigitalMala';

const {REPETITION_TARGETS,MALA_TARGETS,advance,newSession,finishSession,rollover,validTarget,sessionTargetRepetitions,sessionProgress,completionMessage}=experience;
const Button=({children,onPress,disabled=false,selected=false})=><TouchableOpacity accessibilityRole="button" disabled={disabled} accessibilityState={{disabled,selected}} onPress={onPress} style={[s.button,selected&&s.selected,disabled&&s.disabled]}><Text style={[s.buttonText,selected&&s.selectedText]}>{children}</Text></TouchableOpacity>;
export default function MantraJapaScreen(){
  const {id}=useLocalSearchParams(),insets=useSafeAreaInsets();
  const [mantra,setMantra]=useState(null),[practice,setPractice]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [interaction,setInteraction]=useState('manual'),[audioState,setAudioState]=useState('idle'),[audioError,setAudioError]=useState(''),[storageError,setStorageError]=useState(false),[custom,setCustom]=useState('');
  const current=useRef(null),controller=useRef(null),alive=useRef(true),acceptTap=useRef(mantraPractice.createTapGuard(350)).current;
  const pronunciation=useMantraPronunciation(mantra&&!mantra.sanskrit_text_corrupted?mantra.sanskrit_text:null),pausePronunciation=pronunciation.pause;
  const source=useMemo(()=>mantra&&!mantra.sanskrit_text_corrupted?guided.selectGuidedAudio(mantra.audio_artifacts,mantra.id):null,[mantra]);
  const save=useCallback(value=>{current.current=value;setPractice(value);persistPractice(value).then(()=>{if(alive.current)setStorageError(false);}).catch(()=>{if(alive.current){setStorageError(true);controller.current?.pause();}});},[]);
  const increment=useCallback(()=>{if(!current.current)return;const before=sessionProgress(current.current),next=advance(current.current),after=sessionProgress(next);if(after.completedMalas>before.completedMalas)Vibration.vibrate([0,55,70,55]);save(next);},[save]);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useFocusEffect(useCallback(()=>{let active=true;current.current=null;setPractice(null);setMantra(null);setError('');setInteraction('manual');
    Promise.all([mantraCatalog.fetchMantraById(backendFetch,String(id||'')),loadPractice(String(id||''))]).then(([value,saved])=>{if(!active)return;if(!value){setError('This Mantra is unavailable.');return;}setMantra(value);addRecentId(value.id);current.current=saved;setPractice(saved);})
      .catch(()=>{if(active)setError('Your practice could not be loaded. Please retry.');});
    return()=>{active=false;controller.current?.pause();pausePronunciation();current.current=null;};
  // Retry intentionally repeats this focused load.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[id,retry,pausePronunciation]));
  useEffect(()=>{if(!source)return;const player=guided.createGuidedController({adapter:createPlaybackAdapter(source),getCount:()=>current.current?.session.count||0,getTarget:()=>current.current?sessionTargetRepetitions(current.current.session):0,onComplete:increment,onState:(state,message)=>{setAudioState(state);setAudioError(message||'');}});controller.current=player;return()=>{controller.current=null;player.dispose();};},[source,increment]);
  useEffect(()=>{const subscription=AppState.addEventListener('change',state=>{if(state!=='active'){controller.current?.pause();pausePronunciation();}else if(current.current)save(rollover(current.current));});const timer=setInterval(()=>{if(current.current&&current.current.date!==experience.localDate())save(rollover(current.current));},30000);return()=>{subscription.remove();clearInterval(timer);};},[save,pausePronunciation]);
  const stopAudio=()=>Promise.all([controller.current?.stop(),pronunciation.pause()]);
  const applySetup=(mode,targetValue)=>{if(!validTarget(targetValue)){Alert.alert('Choose a target','Enter a whole number from 1 to 100,000.');return;}const start=()=>{stopAudio();save(newSession(current.current,{mode,targetValue}));setCustom('');};if(current.current.session.count&&!current.current.session.finished)Alert.alert('Change practice setup?','Your completed repetitions stay in history. This starts a new practice.',[{text:'Cancel',style:'cancel'},{text:'Start new practice',onPress:start}]);else start();};
  const reset=()=>Alert.alert('Reset this practice?','Your completed repetitions stay in today and lifetime totals.',[{text:'Cancel',style:'cancel'},{text:'Reset',style:'destructive',onPress:()=>{stopAudio();save(newSession(current.current,{mode:current.current.session.mode,targetValue:current.current.session.targetValue}));}}]);
  if(error)return <View style={[s.root,s.center]}><Text style={s.text}>{error}</Text><Button onPress={()=>setRetry(value=>value+1)}>Retry</Button><Button onPress={()=>router.back()}>Go back</Button></View>;
  if(!mantra||!practice)return <View style={[s.root,s.center]}><ActivityIndicator color="#F4B76D"/><Text style={s.text}>Loading your practice…</Text></View>;
  const session=practice.session,progress=sessionProgress(practice),finished=session.finished,targets=session.mode==='MALA_ROUNDS'?MALA_TARGETS:REPETITION_TARGETS;
  return <View style={[s.root,{paddingTop:insets.top}]}><View style={s.header}><Button onPress={()=>router.back()}>‹ Back</Button><Text numberOfLines={2} style={s.heading}>{mantra.canonical_name}</Text></View>
    <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[s.content,{paddingBottom:insets.bottom+48}]}>
      <Text selectable={!mantra.sanskrit_text_corrupted} style={s.sanskrit}>{mantra.sanskrit_text_corrupted?'Sacred text under review':mantra.sanskrit_text}</Text>
      <View style={s.topActions}><Button disabled={mantra.sanskrit_text_corrupted} onPress={pronunciation.isPlaying?pronunciation.pause:async()=>{await controller.current?.stop();pronunciation.play();}}>{pronunciation.isPlaying?'Stop pronunciation':'Learn pronunciation'}</Button><Button onPress={()=>router.push({pathname:'/mantra_detail',params:{id:mantra.id,preparation:'1'}})}>View preparation</Button></View>
      <Text style={s.note}>The pronunciation aid uses device speech and is not verified recitation.</Text>{pronunciation.error?<Text accessibilityRole="alert" style={s.warning}>{pronunciation.error}</Text>:null}

      <View style={s.setup}><Text style={s.label}>Practice mode</Text><View style={s.row}><Button selected={session.mode==='REPETITIONS'} onPress={()=>applySetup('REPETITIONS',108)}>Repetitions</Button><Button selected={session.mode==='MALA_ROUNDS'} onPress={()=>applySetup('MALA_ROUNDS',1)}>Mala rounds</Button></View>
        <Text style={s.setupTitle}>{session.mode==='MALA_ROUNDS'?'Complete 108-bead mala rounds':'Choose repetitions'}</Text><View style={s.row}>{targets.map(value=><Button key={value} selected={session.targetValue===value} onPress={()=>applySetup(session.mode,value)}>{value}</Button>)}</View>
        <View style={s.row}><TextInput accessibilityLabel={`Custom ${session.mode==='MALA_ROUNDS'?'mala round':'repetition'} target`} style={s.input} value={custom} onChangeText={setCustom} keyboardType="number-pad" placeholder="Custom" placeholderTextColor="#BBA18A"/><Button onPress={()=>applySetup(session.mode,Number(custom))}>Set</Button></View>
        <Text style={s.note}>{session.mode==='MALA_ROUNDS'?`${session.targetValue} ${session.targetValue===1?'mala':'malas'} = ${progress.target} repetitions. The meru bead is a marker and is not counted.`:'This is your personal counting target, not mantra-specific practice guidance.'}</Text>
      </View>

      <Text style={s.label}>Guided audio</Text><View style={s.row}><Button selected={interaction==='manual'} onPress={()=>{stopAudio();setInteraction('manual');}}>Off · manual</Button><Button selected={interaction==='guided'} disabled={!source} onPress={async()=>{await pronunciation.pause();setInteraction('guided');}}>On</Button></View>
      {!source?<Text style={s.note}>Guided audio will be available when a reviewed recitation is published.</Text>:<Text style={s.note}>{source.synthetic?'Reviewed synthetic recitation':'Verified human recitation'}</Text>}

      <DigitalMala count={session.count} currentMala={progress.currentMala} totalMalas={progress.intendedMalas} disabled={interaction!=='manual'||finished||storageError} onPress={()=>{if(interaction==='manual'&&!current.current.session.finished&&acceptTap()){Vibration.vibrate(8);increment();}}}/>
      <View style={s.stats}><View style={s.statBox}><Text style={s.statValue}>{progress.currentBead}</Text><Text style={s.statLabel}>Current bead / 108</Text></View><View style={s.statBox}><Text style={s.statValue}>{progress.completedMalas}</Text><Text style={s.statLabel}>Malas complete</Text></View><View style={s.statBox}><Text style={s.statValue}>{session.count}</Text><Text style={s.statLabel}>Repetitions</Text></View></View>
      <Text style={s.progress}>{session.mode==='MALA_ROUNDS'?`${progress.completedMalas} of ${session.targetValue} malas`:`${session.count} of ${progress.target} repetitions`}</Text>
      <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:progress.target,now:session.count}} style={s.track}><View style={[s.fill,{width:`${progress.fraction*100}%`}]}/></View>
      {interaction==='guided'?<><Text style={s.note}>{audioState==='paused'?'Paused. Resume restarts the unfinished repetition.':audioState==='playing'?'Playing one complete repetition…':'Ready for guided Japa.'}</Text><View style={s.row}><Button disabled={finished||storageError} onPress={()=>controller.current?.start()}>{audioState==='paused'?'Resume':'Start'}</Button><Button onPress={()=>controller.current?.pause()}>Pause</Button></View>{audioError?<Text accessibilityRole="alert" style={s.warning}>{audioError}</Text>:null}</>:null}
      {finished?<View style={s.completion}><Text style={s.heading}>Japa complete</Text><Text style={s.text}>{completionMessage(mantra.completion_recitation)}</Text><Text style={s.note}>{session.count} repetitions · {progress.completedMalas} completed 108-bead {progress.completedMalas===1?'mala':'malas'}</Text><Button onPress={()=>applySetup(session.mode,session.targetValue)}>Start a new practice</Button></View>:<View style={s.row}><Button onPress={reset}>Reset</Button><Button onPress={()=>{stopAudio();save(finishSession(current.current));}}>End practice</Button></View>}
      {storageError?<View><Text accessibilityRole="alert" style={s.warning}>Progress could not be saved. Counting is paused; keep this screen open and retry.</Text><Button onPress={()=>save(current.current)}>Retry saving</Button></View>:null}
      <View style={s.today}><Text style={s.label}>Today</Text><Text style={s.text}>{practice.repetitions_today} repetitions · {practice.completed_malas_today} complete malas</Text><Text style={s.note}>{practice.streak} day practice streak · {practice.total_repetitions} lifetime repetitions</Text><Text style={s.note}>Progress is saved on this device.</Text></View>
    </ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#100A06'},center:{alignItems:'center',justifyContent:'center',padding:24},header:{paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:12},heading:{fontSize:20,color:'#FFF0DE',fontWeight:'700',flex:1},content:{padding:18},text:{color:'#EAD8C4',fontSize:15,lineHeight:24},sanskrit:{color:'#F4D6A5',fontSize:24,lineHeight:38,textAlign:'center',paddingVertical:18},note:{color:'#BEA58E',fontSize:13,lineHeight:21,marginVertical:5},label:{color:'#F4B76D',fontSize:17,fontWeight:'700',marginTop:18,marginBottom:10},setupTitle:{color:'#EAD8C4',fontSize:14,fontWeight:'700',marginTop:14},topActions:{flexDirection:'row',flexWrap:'wrap',gap:8,justifyContent:'center'},setup:{padding:14,borderRadius:18,backgroundColor:'#1D120A',marginTop:18},row:{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:6},button:{minHeight:48,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'#63462D',borderRadius:14,paddingHorizontal:15,paddingVertical:10},buttonText:{color:'#F4D6A5',fontSize:14,textAlign:'center'},selected:{backgroundColor:'#E78933',borderColor:'#F4B76D'},selectedText:{color:'#180B05',fontWeight:'800'},disabled:{opacity:.4},input:{minHeight:48,minWidth:120,flexGrow:1,color:'#FFF0DE',borderWidth:1,borderColor:'#63462D',borderRadius:14,paddingHorizontal:14},stats:{flexDirection:'row',gap:8},statBox:{flex:1,minWidth:90,backgroundColor:'#1D120A',borderRadius:14,padding:12,alignItems:'center'},statValue:{color:'#F4B76D',fontSize:22,fontWeight:'800'},statLabel:{color:'#BEA58E',fontSize:10,textAlign:'center',marginTop:4},progress:{fontSize:18,fontWeight:'700',color:'#F4B76D',textAlign:'center',marginTop:16},track:{height:6,backgroundColor:'#46301F',borderRadius:4,overflow:'hidden',marginVertical:14},fill:{height:6,backgroundColor:'#F4B76D'},completion:{padding:20,backgroundColor:'#2C1D0E',borderRadius:20,marginVertical:16,gap:10},today:{marginTop:8,paddingTop:8,borderTopWidth:1,borderTopColor:'#46301F'},warning:{color:'#FFC8B7',lineHeight:22,marginVertical:12}});
