import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Animated, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, Vibration, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { getMantraById } from '../data/mantraV2';
import { safeGet, safeSet, KEYS } from '../utils/storage';
import { saveJapaSession, getMantraStreak } from '../utils/mantraAudio';

const TARGETS=[11,21,27,54,108];
const todayKey=()=>`japa_${new Date().toDateString()}`;
export default function MantraJapaScreen(){
  const {id}=useLocalSearchParams(); const insets=useSafeAreaInsets(); const mantra=getMantraById(String(id||''));
  const [count,setCount]=useState(0); const [target,setTarget]=useState(108); const [today,setToday]=useState(0); const [streak,setStreak]=useState(0); const [custom,setCustom]=useState(''); const scale=useRef(new Animated.Value(1)).current; const lock=useRef(false);
  useEffect(()=>{Promise.all([safeGet(KEYS.JAPA_COUNT,0),safeGet(KEYS.JAPA_TARGET,108),safeGet(todayKey(),0),getMantraStreak()]).then(([c,t,d,s])=>{setCount(Number(c)||0);setTarget(Number(t)||108);setToday(Number(d)||0);setStreak(Number(s)||0);});},[]);
  const choose=value=>{setTarget(value);setCount(0);safeSet(KEYS.JAPA_TARGET,value);safeSet(KEYS.JAPA_COUNT,0);};
  const tap=useCallback(()=>{if(lock.current||!mantra)return;lock.current=true;setTimeout(()=>{lock.current=false;},70);Vibration.vibrate(8);Animated.sequence([Animated.timing(scale,{toValue:.9,duration:50,useNativeDriver:true}),Animated.spring(scale,{toValue:1,useNativeDriver:true})]).start();setCount(current=>{const next=current+1;safeSet(KEYS.JAPA_COUNT,next);if(next===target){Vibration.vibrate([0,100,90,100]);saveJapaSession({mantraId:mantra.id,mantraName:mantra.canonical_name,count:target,durationMs:0});Alert.alert('Cycle complete',`${target} repetitions completed.`);}return next;});setToday(current=>{const next=current+1;safeSet(todayKey(),next);return next;});},[mantra,target,scale]);
  if(!mantra)return <View style={[s.root,s.center]}><Text style={s.text}>Mantra entry not found.</Text></View>;
  const cycle=count%target; const malas=Math.floor(count/108);
  return <View style={[s.root,{paddingTop:insets.top,paddingBottom:insets.bottom}]}><View style={s.header}><TouchableOpacity style={s.backButton} onPress={()=>router.back()}><Text style={s.back}>‹</Text></TouchableOpacity><Text numberOfLines={2} style={s.headerTitle}>Japa · {mantra.canonical_name}</Text></View>
    <ScrollView contentContainerStyle={[s.content,{paddingBottom:Math.max(24,insets.bottom+16)}]}><Text style={s.kicker}>REPETITION COUNT</Text><Text style={s.sanskrit}>{mantra.sanskrit_text}</Text><Text style={s.note}>Targets are counting tools, not claimed scriptural prescriptions.</Text>
      <View style={s.progress}><View style={[s.progressFill,{width:`${Math.min(100,(cycle/target)*100)}%`}]}/></View><Text style={s.progressText}>{cycle} / {target} this cycle · {count} session repetitions</Text><Text style={s.malaText}>{malas} complete 108-repetition {malas===1?'cycle':'cycles'}</Text>
      <View style={s.tapArea}><Animated.View style={{transform:[{scale}]}}><TouchableOpacity accessibilityLabel="Count one repetition" style={s.tapButton} onPress={tap}><Text style={s.count}>{cycle}</Text><Text style={s.tapText}>Tap</Text></TouchableOpacity></Animated.View></View>
      <Text style={s.label}>Choose repetition target</Text><View style={s.targets}>{TARGETS.map(value=><TouchableOpacity key={value} style={[s.target,target===value&&s.targetOn]} onPress={()=>choose(value)}><Text style={s.targetText}>{value}</Text></TouchableOpacity>)}</View>
      <View style={s.customRow}><TextInput keyboardType="number-pad" value={custom} onChangeText={setCustom} placeholder="Custom" placeholderTextColor="#917667" style={s.custom}/><TouchableOpacity style={s.setButton} onPress={()=>{const value=Number(custom);if(Number.isInteger(value)&&value>0&&value<=10000)choose(value);}}><Text style={s.setText}>Set</Text></TouchableOpacity></View>
      <View style={s.stats}><Text style={s.stat}>Today: {today}</Text><Text style={s.stat}>Streak: {streak} days</Text></View>
      <TouchableOpacity style={s.reset} onPress={()=>{setCount(0);safeSet(KEYS.JAPA_COUNT,0);}}><Text style={s.resetText}>Reset session count</Text></TouchableOpacity>
      {mantra.restriction_note?<Text style={s.warning}>{mantra.restriction_note}</Text>:null}</ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#100702'},center:{alignItems:'center',justifyContent:'center'},header:{minHeight:58,flexDirection:'row',alignItems:'center',paddingHorizontal:10,borderBottomWidth:1,borderBottomColor:'#3D2417'},backButton:{width:44,height:44,justifyContent:'center'},back:{fontSize:34,color:'#F4A261'},headerTitle:{flex:1,flexShrink:1,fontSize:16,fontWeight:'800',color:'#FFF4E8'},content:{padding:16,alignItems:'stretch'},kicker:{fontSize:10,letterSpacing:1.2,textAlign:'center',color:'#B89D89'},sanskrit:{fontSize:22,lineHeight:36,textAlign:'center',color:'#E9C9FF',marginTop:14},note:{fontSize:11,lineHeight:17,textAlign:'center',color:'#AA9180',marginTop:10},progress:{height:8,borderRadius:4,overflow:'hidden',backgroundColor:'#352116',marginTop:22},progressFill:{height:8,backgroundColor:'#E8620A'},progressText:{fontSize:12,textAlign:'center',color:'#E6D1C1',marginTop:8},malaText:{fontSize:11,textAlign:'center',color:'#B89D89',marginTop:4},tapArea:{minHeight:190,alignItems:'center',justifyContent:'center',paddingVertical:20},tapButton:{width:150,height:150,borderRadius:75,alignItems:'center',justifyContent:'center',backgroundColor:'#2B122F',borderWidth:3,borderColor:'#8654A6'},count:{fontSize:38,fontWeight:'900',color:'#F4A261'},tapText:{fontSize:13,color:'#E8D7EF',marginTop:3},label:{fontSize:12,fontWeight:'800',color:'#DCC7B7',marginBottom:8},targets:{flexDirection:'row',flexWrap:'wrap',gap:8},target:{minWidth:50,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:12,borderWidth:1,borderColor:'#56351F'},targetOn:{backgroundColor:'#E8620A',borderColor:'#E8620A'},targetText:{fontSize:13,fontWeight:'800',color:'#FFF1E5'},customRow:{flexDirection:'row',gap:8,marginTop:10},custom:{flex:1,minHeight:48,borderRadius:12,borderWidth:1,borderColor:'#56351F',paddingHorizontal:12,color:'#fff'},setButton:{minWidth:70,minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#47230F'},setText:{color:'#FFD5AE',fontWeight:'800'},stats:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:8,marginTop:18},stat:{color:'#CBB5A5'},reset:{minHeight:48,alignItems:'center',justifyContent:'center',marginTop:14},resetText:{color:'#E99A88'},warning:{fontSize:12,lineHeight:18,color:'#E9C0B7',backgroundColor:'#351A18',padding:12,borderRadius:12,marginTop:12},text:{color:'#fff'}});
